services:
  goo:
    image: ghcr.io/ogrodje/goo:latest
    ports:
      - "0.0.0.0:7778:7777"
    depends_on:
      - pg
    environment:
      - PORT=7777
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=pg
      - POSTGRES_PORT=5432
      - HYGRAPH_ENDPOINT=${HYGRAPH_ENDPOINT}
      - SOURCES=Meetup,Eventbrite,TehnoloskiParkLjubljana,PrimorskiTehnoloskiPark,GZS
    volumes:
      - playwright-cache:/root/.cache/ms-playwright

  pg:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  playwright-cache:
    driver: "local"
    driver_opts:
      type: none
      device: "$HOME/docker-volumes/playwright-cache"
      o: bind