services:
  goo:
    image: ghcr.io/ogrodje/goo:latest
    ports:
      - "0.0.0.0:7778:7777"
    environment:
      - PORT=7777
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=pg
      - POSTGRES_PORT=5432
      - HYGRAPH_ENDPOINT=${HYGRAPH_ENDPOINT}
      - SOURCES=All
      - GOO_ENVIRONMENT=${GOO_ENVIRONMENT}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
      # - SENTRY_DEBUG=true
      # https://github.com/getsentry/sentry-java/blob/main/sentry-opentelemetry/sentry-opentelemetry-agent/README.md#getting-rid-of-exporter-error-messages
      - OTEL_TRACES_EXPORTER=none
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_ENDPOINT=http://keycloak:8080
    volumes:
      - playwright-cache:/root/.cache/ms-playwright
    
    depends_on:
      keycloak:
        condition: service_healthy
      pg:
        condition: service_started

  keycloak:
    build:
      dockerfile: keycloak.Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://pg:5432/${KEYCLOAK_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KEYCLOAK_LOGLEVEL=INFO
    command: 'start-dev'
    depends_on:
      - pg

    healthcheck:
      test: [ "CMD", "curl", "--head", "-fsS","http://localhost:9000/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s

  pg:
    image: postgres:17.5-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  playwright-cache:
    driver: "local"
    driver_opts:
      type: none
      device: "$HOME/docker-volumes/playwright-cache"
      o: bind
