// resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"
addSbtPlugin("com.eed3si9n"   % "sbt-assembly"           % "2.3.1")
addSbtPlugin("com.github.sbt" % "sbt-native-packager"    % "1.11.7")
addSbtPlugin("org.jmotor.sbt" % "sbt-dependency-updates" % "1.2.9")
addSbtPlugin("io.spray"       % "sbt-revolver"           % "0.10.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"           % "2.6.1")
addSbtPlugin("com.github.sbt" % "sbt-dynver"             % "5.1.1")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"          % "0.13.1")
addSbtPlugin("com.github.sbt" % "sbt-javaagent"          % "0.2.0")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"           % "0.14.7")
