name: Build && Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  KUBECONFIG: ogrodje-one-config

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: shimataro/ssh-key-action@v2
        with:
          known_hosts: unnecessary
          key: ${{ secrets.SSH_KEY }}
          name: id_ogrodje_goo
          config: |
            Host ogrodje-one
              User oto
              Hostname ogrodje-one.ogrodje.si
              IdentityFile ~/.ssh/id_ogrodje_goo
              StrictHostKeyChecking no
              ConnectTimeout 60
              ConnectionAttempts 2
              AddKeysToAgent yes
          if_key_exists: fail

      - uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'sbt'

      - uses: sbt/setup-sbt@v1

      - run: sbt "test"

      - name: Run tests and publish
        if: ${{ github.ref == 'refs/heads/master' }}
        run: sbt "docker:publish"

      - name: "Deploy"
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          OGRODJE_ONE_CONFIG: ${{ secrets.OGRODJE_ONE_CONFIG }}
        run: |
          # Write kubeconfig file first
          echo "$OGRODJE_ONE_CONFIG" > ogrodje-one-config
          export KUBECONFIG=ogrodje-one-config
    
          ssh -o "ExitOnForwardFailure yes" \
            -o "ServerAliveInterval 60" \
            -o "ServerAliveCountMax 5" \
            -o "StrictHostKeyChecking no" \
            -o "UserKnownHostsFile /dev/null" \
            -N \
            -L 16443:localhost:16443 oto@ogrodje-one &
          
          sleep 5
          
          # Verify kubeconfig content and server address
          echo "Checking kubeconfig settings..."
          kubectl config view --minify | grep server

          echo "Get pods."
          kubectl get pods -n goo-prod
